//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteDbEntities : DbContext
    {
        public SiteDbEntities()
            : base("name=SiteDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<sayfaform> sayfaform { get; set; }
        public virtual DbSet<Sayfalar> Sayfalar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAltMenu> tblAltMenu { get; set; }
        public virtual DbSet<tblDosya> tblDosya { get; set; }
        public virtual DbSet<tblForm> tblForm { get; set; }
        public virtual DbSet<tblFormIcerik> tblFormIcerik { get; set; }
        public virtual DbSet<tblGaleri> tblGaleri { get; set; }
        public virtual DbSet<tblGaleriResim> tblGaleriResim { get; set; }
        public virtual DbSet<tblLogo> tblLogo { get; set; }
        public virtual DbSet<tblMenu> tblMenu { get; set; }
        public virtual DbSet<yeni> yeni { get; set; }
    }
}
