//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public int DersId { get; set; }
        public string DersAdi { get; set; }
        public string DersIcerik { get; set; }
        public string DersVideo { get; set; }
        public int KursId { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
