//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayfalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sayfalar()
        {
            this.sayfaform = new HashSet<sayfaform>();
            this.tblAltMenu = new HashSet<tblAltMenu>();
        }
    
        public int Id { get; set; }
        public string SayfaAdi { get; set; }
        public string Icerik { get; set; }
        public string headimage { get; set; }
        public bool headaktif { get; set; }
        public bool sayfaaktif { get; set; }
        public int sirano { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> GaleriId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sayfaform> sayfaform { get; set; }
        public virtual tblForm tblForm { get; set; }
        public virtual tblGaleri tblGaleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAltMenu> tblAltMenu { get; set; }
    }
}
