//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblForm()
        {
            this.sayfaform = new HashSet<sayfaform>();
            this.Sayfalar = new HashSet<Sayfalar>();
            this.tblFormIcerik = new HashSet<tblFormIcerik>();
        }
    
        public int id { get; set; }
        public string FormAdi { get; set; }
        public int sira { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sayfaform> sayfaform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sayfalar> Sayfalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFormIcerik> tblFormIcerik { get; set; }
    }
}
