//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormIcerik
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string elementadi { get; set; }
        public string elementtipi { get; set; }
        public int sira { get; set; }
        public bool aktiflik { get; set; }
    
        public virtual tblForm tblForm { get; set; }
    }
}
