//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGaleriResim
    {
        public int Id { get; set; }
        public int Galeri_Id { get; set; }
        public string kresim { get; set; }
        public string bresim { get; set; }
        public int sira { get; set; }
        public string aciklama { get; set; }
    
        public virtual tblGaleri tblGaleri { get; set; }
    }
}
