//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panelim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int id { get; set; }
        public int y_yapan { get; set; }
        public string y_icerik { get; set; }
        public string y_secenek { get; set; }
        public int y_id { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kurs Kurs { get; set; }
    }
}
